name: build-develop-from-scratch

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: "0 7 * * *"

  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build_against_dev_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: dunedaq/sl7-minimal:dev
    defaults:
      run:
        shell: bash
    env:
      DBT_AREA_FILE: "dbt-settings"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    

    - name: Checkout daq-buildtools
      uses: actions/checkout@v3
      with:
        repository: DUNE-DAQ/daq-buildtools
        path: daq-buildtools

    - name: Checkout daq-release
      uses: actions/checkout@v3
      with:
        repository: DUNE-DAQ/daq-release
        path: daq-release
        
    - name: setup dev area and checkout code
      run: |
          source $GITHUB_WORKSPACE/daq-buildtools/dbt-setup-env.sh
          dbt-create.sh -r $GITHUB_WORKSPACE/daq-release/configs dunedaq-develop dev
          cd dev
          cp $GITHUB_WORKSPACE/daq-release/configs/dunedaq-develop/release_manifest.sh .
          $GITHUB_WORKSPACE/daq-release/scripts/checkout-package.sh -f ./release_manifest.sh -a -b develop -o sourcecode
          
    - name: checkout package for CI
      uses: actions/checkout@v3
      with:
        path: ${{ github.repository }}
    
    - name: setup build env and build the dev release
      run: |
          export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          source $GITHUB_WORKSPACE/daq-buildtools/dbt-setup-env.sh
          cd $GITHUB_WORKSPACE/dev
          rm -rf sourcecode/$REPO
          cp -pr $GITHUB_WORKSPACE/DUNE-DAQ/$REPO $GITHUB_WORKSPACE/dev/sourcecode
          cd $GITHUB_WORKSPACE/dev
          export DBT_AREA_ROOT=$PWD
          export DBT_AREA_FILE="dbt-settings"
          source ${DBT_AREA_ROOT}/${DBT_AREA_FILE}
          setup_ups_product_areas || true
          setup -B python ${dune_python_version} || true
          source ${DBT_AREA_ROOT}/${DBT_VENV}/bin/activate 
          setup_ups_products dune_devtools || true
          setup_ups_products dune_systems || true
          setup_ups_products dune_externals || true
          export DBT_INSTALL_DIR=${DBT_AREA_ROOT}/install
          export DBT_SETUP_BUILD_ENVIRONMENT_SCRIPT_SOURCED=1
          dbt-build.sh --install
          $GITHUB_WORKSPACE/daq-release/scripts/upsify-daq-pkgs.py -w $GITHUB_WORKSPACE/dev -o /tarballs -p $REPO
          
    - name: upload UPS tarball and log file
      uses: actions/upload-artifact@v2
      with:
        name: ups_package
        path: /tarballs

    - name: upload build log file
      uses: actions/upload-artifact@v2
      with:
        name: build_log
        path: ${{ github.workspace }}/dev/log
